[simulation]
  name    = "custom_spatial_distribution"
  engine  = "srpic"
  runtime = 2.0

[grid]
  resolution = [128, 128]
  extent     = [[-1.5, 1.5], [-1.0, 2.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["REFLECT", "REFLECT"], ["REFLECT", "REFLECT"]]

[scales]
  larmor0    = 1.0
  skindepth0 = 1.0

[algorithms]

  [algorithms.deposit]
    enable = false

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0        = 16.0
  use_weights = true

  [[particles.species]]
    label    = "e+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 1e6

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e6

[output]
  interval = 1

  [output.fields]
    quantities = ["N_1_2"]

  [output.particles]
    stride = 10

  [output.spectra]
    enable = false

[checkpoint]
  keep = 0
