[simulation]
title   = "drift"
runtime = 2000.0

[domain]
resolution = [128, 128]
extent     = [-16.0, 16.0, -16.0, 16.0]
boundaries = [["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL             = 0.5
current_filters = 20

[units]
ppc0       = 8.0
larmor0    = 1.0
skindepth0 = 1.0

[particles]
n_species = 2
shuffle_interval = 1

[species_1]
label    = "e-_p"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8

[species_2]
label    = "e+_p"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8

[problem]
drift_p       = 10.0
temperature_p = 0.08

[output]
fields        = ["B", "E", "Rho"]
particles     = ["X", "U"]
prtl_stride   = 1
fields_stride = 1
format        = "HDF5"
interval_time = 50.0
