[simulation]
title   = "GR-411-massive"
runtime = 10000.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.001
a           = 0.0
sph_rabsorb = 95.0
resolution  = [128, 128]
extent      = [0.1, 100.0]
boundaries  = [["OPEN", "ABSORB"], ["AXIS"]]

[algorithm]
CFL             = 10.0
correction      = 1.0
current_filters = 4
fieldsolver_ON  = false

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[particles]
n_species    = 1

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e2

[output]
fields        = []
particles     = ["X", "U"]
format        = "HDF5"
interval_time = 10.0

[problem]
r0   = [68.600387]
th0  = [1.570796]
ph0  = [0.000000]
ur0  = [0.029637]
uth0 = [0.000000]
uph0 = [3.900000]

[diagnostics]
interval        = 101
log_level       = "ERROR"
blocking_timers = true
