baseURL = "https://haykh.github.io/entity"
languageCode = 'en-us'
title = '"Entity" Particle-in-cell Code'
theme = 'hugo-geekdoc'

pluralizeListTitles = false

# pygmentsUseClasses = true
# pygmentsCodeFences = true
disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = 'native'

[taxonomies]
   tag = "tags"

[params]
  geekdocMenuBundle = true
