[simulation]
title   = "MagnetosphereG100"
runtime = 350.0

[domain]
resolution = [2048,2048]
extent     = [1.0, 50.0]
boundaries = [["CUSTOM", "ABSORB"], ["AXIS"]]
qsph_r0    = 0.0
qsph_h     = 0.0

[algorithm]
CFL             = 0.75
current_filters = 8
extforce_ON   = true

[GCA]
EovrB_max  = 0.9
larmor_max = 10.0

[units]
ppc0       = 5.0
larmor0    = 2.5e-5
skindepth0 = 0.01

[particles]
sort_interval = 100
n_species        = 6
use_weights      = true

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e8
pusher   = "Boris,GCA"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e8
pusher   = "Boris,GCA"

[species_3]
label    = "ppar"
mass     = 0.0
charge   = 0.0
maxnpart = 1e4
n_payloads = 1

[species_4]
label    = "pperp"
mass     = 0.0
charge   = 0.0
maxnpart = 1e4
n_payloads = 1

[species_5]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 2e8
pusher   = "Boris,GCA"

[species_6]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 2e8
pusher   = "Boris,GCA"

[problem]
atm_T           = 0.1
atm_contrast    = 10.0
atm_h           = 0.02
atm_buff        = 0.1
psr_Bsurf       = 1.0
psr_omega       = 0.023
psr_spinup_time = 10.0
psr_field_mode  = 2
fid_freq = 0.005
bq = 0.1

[output]
fields        = ["N_1", "N_2", "N_5", "N_6", "B", "E", "J"]
format        = "HDF5"
fields_stride = 2
mom_smooth    = 2
interval_time = 1.0
