[simulation]
title   = "Deposit"
runtime = 2.0

[domain]
resolution = [512, 512]
extent     = [-1.0, 1.0, -1.0, 1.0]
boundaries = [["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL             = 0.5
current_filters = 8

[units]
ppc0       = 4.0
larmor0    = 1e-2
skindepth0 = 0.1

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 25.0

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 25.0

[problem]
x1  = [-0.71, -0.69, 0.91, -0.34, -0.69, -0.09, 0.11, -0.71, -0.95, -0.95, 0.8, -0.8]
x2  = [-0.29, -0.4, 0.31, 0.45, -0.64, 0.53, -0.37, -0.31, 0.33, 0.49, 0.8, 0.8]
ux1 = [-9.13, 3.97, 1.22, 3.68, 5.99, -5.33, -0.77, -0.21, 5.84, 3.73, 1.0, -1.0]
ux2 = [0.35, 0.40, 7.41, -5.31, 2.77, -2.15, -2.53, 0.07, 0.97, 6.33, 1.0, 1.0]

[output]
fields        = ["E", "J", "divE"]
interval_time = 0.025
prtl_stride   = 1
flds_stride   = 1
particles     = ["X", "U"]
format        = "HDF5"

[diagnostics]
log_level = "DEBUG"
