[simulation]
  name = "wald"
  engine = "grpic"
  runtime = 100.0

[grid]
  resolution = [256,256]
  extent = [[0.8, 8.0]]

  [grid.metric]
    metric = "qkerr_schild"
    qsph_r0 = 0.0 
    qsph_h = 0.0
    ks_a = 0.95

  [grid.boundaries]
    fields = [["ABSORB"]]
    particles = [["ABSORB"]]

    [grid.boundaries.absorb]
      ds = 0.5

[scales]
  larmor0 = 0.0025
  skindepth0 = 0.05

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.toggles]
    deposit = true
    fieldsolver = true

[particles]
  ppc0 = 8.0
  use_weights = true
  sort_interval = 100

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e6
  pusher = "Boris"
  
  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e6
  pusher = "Boris"

[setup]
  multiplicity = 1.0
  sigma_max = 10.0
  xi_min = [1.2, 0.1]
  xi_max = [7.5, 3.04159265]

[output]
  format = "hdf5"

  [output.fields]
    interval_time = 1.0
    quantities = ["D", "B", "J", "N_1", "N_2", "Nppc_1", "Nppc_2"]
    
  [output.particles]
    enable = false

  [output.spectra]
    enable = false

[diagnostics]
  interval = 2
  colored_stdout = true
  blocking_timers = true
