[simulation]
title   = "GR"
runtime = 5.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.001
a           = 0.0
sph_rabsorb = 19.0
resolution  = [512, 512]
extent      = [0.8, 20.0]
boundaries  = [["OPEN", "ABSORB"], ["AXIS"]]

[algorithm]
CFL             = 0.5
correction      = 1.0
current_filters = 4
fieldsolver_ON  = false

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[particles]
n_species    = 1

[species_1]
label    = "photons"
mass     = 0.0
charge   = 0.0
maxnpart = 1e4

[output]
fields    = ["Rho", "N"]
particles = ["X", "U"]
format    = "HDF5"
interval  = 10

[problem]
r0   = [18.000, 18.000, 18.000, 18.000]
th0  = [1.171, 1.321, 0.871, 0.371]
ur0  = [-9.211, -9.689, -7.648, -3.624]
uth0 = [-3.894, -2.474, -6.442, -9.320]
uph0 = [0.000, 0.000, 0.000, 0.000]
