[simulation]
title   = "GR"
runtime = 5.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.0
a           = 0.95
sph_rabsorb = 48.0
resolution  = [512, 512]
extent      = [0.8, 50.0]
boundaries  = [["OPEN", "ABSORB"], ["AXIS"]]

[algorithm]
CFL        = 0.5
deposit_ON = false

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[output]
fields        = ["A"]
fields_stride = 4

[diagnostics]
log_level       = "DEBUG"
blocking_timers = true
