[simulation]
  name    = "em_vacuum"
  engine  = "srpic"
  runtime = 2.0

[grid]
  resolution = [512, 512]
  extent     = [[-1.0, 1.0], [-1.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 0.0001
  skindepth0 = 0.01

[algorithms]

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 4.0

  [[particles.species]]
    label = "e-_p"
    mass = 1.0
    charge = -1.0
    maxnpart = 1e7

  [[particles.species]]
    label = "e+_p"
    mass = 1.0
    charge = 1.0
    maxnpart = 1e7

[setup]
  temp = 0.001
  amplitude = 1000.0
  nwave_x = 1.0
  nwave_y = 1.0
  nwave_z = 1.0
  frequency = 1.0

[output]
  format        = "BP5"
  interval      = 10

  [output.fields]
    quantities = ["E", "B", "J"]

[diagnostics]
  colored_stdout = false
