[simulation]
  name = "rec-gravity"
  engine = "srpic"
  runtime = 20.0

[grid]
  resolution = [2000, 4000]
  extent = [[-0.5, 0.5], [-1.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]
    
[scales]
  larmor0 = 3.1e-4
  skindepth0 = 1e-3

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.45

[particles]
  ppc0 = 8.0

  [[particles.species]]
    label = "e-"
    mass = 1.0
    charge = -1.0
    maxnpart = 1e8

  [[particles.species]]
    label = "e+"
    mass = 1.0
    charge = 1.0
    maxnpart = 1e8

[setup]
  Bmag = 1.0
  width = 0.04
  bg_temp = 1e-4
  overdensity = 3.0
  angle = 0.0
  
[output]
  format = "hdf5"
  interval_time = 0.36

  [output.fields]
    quantities = ["N_1", "N_2", "E", "B", "J", "T00_1", "T00_2"]
