[simulation]
  name = "wald"
  engine = "grpic"
  runtime = 110.0

[grid]
  resolution = [128,128]
  extent = [[1.2, 8.0]]

  [grid.metric]
    metric = "kerr_schild"
    qsph_r0 = 0.0 
    qsph_h = 0.0
    ks_a = 0.95

  [grid.boundaries]
    fields = [["ABSORB"]]
    particles = [["ABSORB"]]

    [grid.boundaries.absorb]
      ds = 0.5

[scales]
  larmor0 = 1.0
  skindepth0 = 1.0

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.toggles]
    deposit = false
    fieldsolver = true

[particles]
  ppc0 = 8.0
  use_weights = true
  sort_interval = 100

#  [[particles.species]]
#  label = "e-"
#  mass = 1.0
#  charge = -1.0
#  maxnpart = 2e6
#  pusher = "Boris"
#
#  [[particles.species]]
#  label = "e+"
#  mass = 1.0
#  charge = 1.0
#  maxnpart = 2e6
#  pusher = "Boris"

[setup]

[output]
  format = "hdf5"

  [output.fields]
    interval_time = 1.0
    quantities = ["D", "H", "B", "J"]

  [output.particles]
    interval_time = 1.0
    quantities = ["X", "U"]

  [output.spectra]
    enable = false

[diagnostics]
  interval = 1
