[simulation]
title   = "Langmuir"
runtime = 10.0

[domain]
resolution = [512, 512]
extent     = [-1.0, 1.0, -1.0, 1.0]
boundaries = [["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL             = 0.9
correction      = 1.0
current_filters = 8

[units]
ppc0       = 16.0
larmor0    = 0.1
skindepth0 = 0.1

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e7

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e7
pusher   = "None"

[problem]
amplitude   = 1e-2
temperature = 1e-2
nx          = 2

[output]
format        = "HDF5"
fields        = ["E", "Rho_1"]
fields_stride = 1
interval_time = 0.025
