[simulation]
title   = "Magnetosphere"
runtime = 200.0

[domain]
resolution = [1560, 1024]
extent     = [1.0, 100.0]
boundaries = [["CUSTOM", "ABSORB"], ["AXIS"]]
qsph_r0    = 0.0
qsph_h     = 0.0

[algorithm]
CFL             = 0.75
current_filters = 8
extforce_ON     = true

[GCA]
EovrB_max  = 0.9
larmor_max = 0.05

[units]
ppc0       = 4.0
larmor0    = 2.5e-5
skindepth0 = 0.01

[particles]
sort_interval = 100
n_species        = 2
use_weights      = true

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 2e8
pusher   = "Boris,GCA"

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 2e8
pusher   = "Boris,GCA"

[problem]
atm_T           = 0.1
atm_contrast    = 4.0
atm_h           = 0.05
atm_buff        = 0.1
psr_Bsurf       = 1.0
psr_omega       = 0.125
psr_spinup_time = 5.0
psr_field_mode  = 2

[output]
fields        = ["N_1", "N_2", "B", "E"]
format        = "HDF5"
fields_stride = 2
mom_smooth    = 2
interval_time = 0.25
