#!/usr/bin/env bash

build_dir=""
extra_flags=""
nproc=$(nproc)
with_pgens=false
run_pgens=false

make_plots=false

with_tests=false
run_tests=false

while [[ $# -gt 0 ]]; do
  case "$1" in
  --build)
    if [[ -z "${2:-}" || "$2" == --* ]]; then
      echo "Error: --build requires a value"
      exit 1
    fi
    build_dir="$2"
    shift 2
    ;;
  --with_pgens)
    with_pgens=true
    run_pgens=true
    if [[ "$2" == "compile" ]]; then
      run_pgens=false
      shift 2
    else
      shift
    fi
    ;;
  --with_tests)
    with_tests=true
    run_tests=true
    if [[ "$2" == "compile" ]]; then
      run_tests=false
      shift 2
    else
      shift
    fi
    ;;
  --make_plots)
    make_plots=true
    shift
    ;;
  --flags)
    extra_flags="$2"
    shift 2
    ;;
  --nproc)
    if [[ -z "${2:-}" || "$2" == --* ]]; then
      echo "Error: --nproc requires a value"
      exit 1
    fi
    nproc="$2"
    shift 2
    ;;
  *)
    echo "Unknown option: $1"
    echo "Usage: $0 --build <build_dir> [--flags <extra_cmake_flags>] [--with_pgens <compile | >] [--with_tests <compile | >] [--make_plots] [--nproc <num_threads>]"
    exit 1
    ;;
  esac
done

if [ "${with_pgens}" = false ] && [ "${with_tests}" = false ]; then

  echo "Error: At least one of --with_pgens or --with_tests must be specified"
  exit 1

fi

if [ "${make_plots}" = true ] && [ "${run_pgens}" = false ]; then

  echo "Error: --make_plots requires --with_pgens to be specified"
  exit 1

fi

if [ "${make_plots}" = true ]; then

  if ! python3 -c "import nt2" &>/dev/null; then
    echo "Error: nt2py python package is not installed. Please install it with 'pip install nt2py' and try again or remove --make_plots."
    exit 1
  fi

  if ! command -v ffmpeg &>/dev/null; then
    echo "Error: ffmpeg is not installed. Please install it and try again or remove --make_plots."
    exit 1
  fi

fi

if [ "${build_dir}" != "" ]; then

  pgens=$(find pgens/ -mindepth 2 -name "pgen.hpp" -exec dirname {} \; | sed 's|^pgens/||' | paste -sd ";" -)
  example_pgens=$(find examples/ -name "pgen.hpp" -exec dirname {} \; | sed 's|^examples/|./examples/|' | paste -sd ";" -)
  tutorial_pgens=$(find tutorials/ -name "pgen.hpp" -exec dirname {} \; | sed 's|^tutorials/|./tutorials/|' | paste -sd ";" -)
  all_pgens="${pgens};${example_pgens};${tutorial_pgens}"

  if [ "${with_pgens}" = true ]; then
    extra_flags="${extra_flags} -D pgens=${all_pgens}"
  fi

  if [ "${with_tests}" = true ]; then
    extra_flags="${extra_flags} -D TESTS=ON"
  fi

  (
    cmake -B ${build_dir} ${extra_flags} &&
      cmake --build ${build_dir} -j ${nproc}
  ) || exit 1

  if [ "${run_tests}" = true ]; then
    ctest --test-dir ${build_dir} --output-on-failure
  fi

  if [ "${run_pgens}" = true ]; then
    temp_dir="$(realpath "${build_dir}")/runs"

    for pgen in $(echo ${example_pgens} | tr ";" "\n"); do
      if [[ "${pgen}" == *"particle_update"* ]]; then
        continue
      fi
      pgen_alt=$(echo "${pgen}" | sed 's|./examples/|examples_|')
      mkdir -p "${temp_dir}/${pgen_alt}"
      cp "${build_dir}/${pgen_alt}/src/entity_${pgen_alt}.xc" "${temp_dir}/${pgen_alt}/"
      find "${pgen}" -type f -name "*.py" -exec cp {} "${temp_dir}/${pgen_alt}/" \;
      find "${pgen}" -type f -name "*.toml" -exec cp {} "${temp_dir}/${pgen_alt}/" \;

      inputs=$(find "${temp_dir}/${pgen_alt}" -type f -name "*.toml")

      for toml_file in ${inputs}; do
        toml_basename=$(basename "${toml_file}")
        echo "Running pgen: ${pgen} with input ${toml_basename}"
        if [[ "${extra_flags}" == *"mpi=ON"* ]]; then
          (cd "${temp_dir}/${pgen_alt}" && mpiexec -n 2 ./entity_${pgen_alt}.xc -input "${toml_basename}")
        else
          (cd "${temp_dir}/${pgen_alt}" && ./entity_${pgen_alt}.xc -input "${toml_basename}")
        fi
      done
      if [ "${make_plots}" = true ]; then
        python_scripts=$(find "${temp_dir}/${pgen_alt}" -type f -name "*.py")
        for py_file in ${python_scripts}; do
          py_basename=$(basename "${py_file}")
          echo "Running python script: ${py_basename} for pgen ${pgen}"
          (cd "${temp_dir}/${pgen_alt}" && python3 "${py_basename}")
        done
      fi
    done

    if [ "${make_plots}" = true ]; then
      mkdir -p "${temp_dir}/results"
      find "${temp_dir}" -maxdepth 2 -type f \( -name "*.png" -o -name "*.mp4" \) -exec mv {} "${temp_dir}/results/" \;
    fi
  fi

  if [ "${make_plots}" = true ]; then
    echo "Plots and videos generated by the pgens have been saved to ${temp_dir}/results/"
  fi

else

  echo "Error: --build <build_dir> must be specified"
  exit 1

fi
