[simulation]
  name    = "shock"
  engine  = "srpic"
  runtime = 30000.0

[grid]
  resolution = [16384, 128]
  extent     = [[0.0, 8000.0], [-31.25, 31.25]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["CONDUCTOR", "MATCH"], ["PERIODIC"]]
    particles = [["REFLECT", "ABSORB"], ["PERIODIC"]]
    
[scales]
  larmor0    = 100.0
  skindepth0 = 1.0

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 8.0

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e8

  [[particles.species]]
    label    = "p+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 1e8

[setup]
  drift_ux    = 0.1
  temperature = 1e-4
  Bmag = 1.0
  Btheta = 0.0
  Bphi = 0.0

[output]
  interval_time = 500.0
  format        = "hdf5"
  
  [output.fields]
    quantities = ["N_1", "N_2", "B", "E"]

  [output.particles]
    enable = true
    stride = 10 

  [output.spectra]
    enable = false

