[simulation]
  name = "em_vacuum"
  engine = "srpic"
  runtime = 2.0

[grid]
  resolution = [1024, 1024]
  extent = [[-1.0, 1.0], [-1.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["ATMOSPHERE","ATMOSPHERE"], ["PERIODIC"]]
    particles = [["ATMOSPHERE","ATMOSPHERE"], ["PERIODIC"]]

    [grid.boundaries.absorb]
      ds = 1.0

    [grid.boundaries.atmosphere]
      temperature = 0.1
      density = 40.0
      height = 0.05
      species = [1, 2]
      ds = 0.25

[scales]
  larmor0 = 5e-6
  skindepth0 = 0.01

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.gca]
    e_ovr_b_max = 0.9
    larmor_max = 100.0

[particles]
  ppc0 = 4.0
  use_weights = true
  sort_interval = 100

  [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e8
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e8
  pusher = "Boris,GCA"

 [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 1e4
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 1e4
  pusher = "Boris,GCA"

 [[particles.species]]
  label = "e-"
  mass = 1.0
  charge = -1.0
  maxnpart = 2e8
  pusher = "Boris,GCA"

  [[particles.species]]
  label = "e+"
  mass = 1.0
  charge = 1.0
  maxnpart = 2e8
  pusher = "Boris,GCA"

[setup]
  Bsurf = 1.0
  omega = 0.0125

[output]
  format = "hdf5"

  [output.fields]
    interval_time = 0.5
    quantities = ["N_1", "N_2", "N_5", "N_6", "B", "E", "J"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false

[diagnostics]
  interval = 100
