[simulation]
title   = "RICS"
runtime = 10000.0

[domain]
resolution = [10000]
extent     = [1000.0, 11000.0]
boundaries = [["PERIODIC"]]

[algorithm]
CFL            = 0.5
fieldsolver_ON = false
deposit_ON     = false

[units]
ppc0       = 1.0
larmor0    = 0.1
skindepth0 = 1.0

[particles]
n_species = 1

[species_1]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e2
pusher   = "Boris,GCA"

[problem]
rstar = 1000.0
fid_freq = 0.000978474
bq = 0.1

[output]
fields        = ["B"]
particles   = ["X", "U"]
format      = "HDF5"
prtl_stride = 1
interval = 100

