[simulation]
title   = "Cooling"
runtime = 100.0

[domain]
resolution = [100, 100, 100]
extent     = [-10.0, 10.0, -10.0, 10.0, -10.0, 10.0]
boundaries = [["PERIODIC"], ["PERIODIC"], ["PERIODIC"]]

[algorithm]
CFL            = 0.1
fieldsolver_ON = false
deposit_ON     = false

[synchrotron]
gamma_rad = 10.0

[units]
ppc0       = 1.0
larmor0    = 0.1
skindepth0 = 1.0

[particles]
n_species = 1

[species_1]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e2
pusher   = "Boris,GCA"
cooling  = "Synchrotron"

[problem]
ux = 50.0
uy = 0.0
uz = 50.0

[output]
particles   = ["X", "U"]
format      = "HDF5"
prtl_stride = 1
# interval_time = 0.5
interval = 10

[diagnostics]
log_level = "DEBUG"
