[simulation]
  name    = "compton_kompaneets"
  engine  = "srpic"
  runtime = 5.0

[grid]
  resolution = [128, 128]
  extent     = [[0.0, 1.0], [0.0, 1.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 1.0
  skindepth0 = 1.0

[two_body]
  thomson_optical_depth = 60.0

  [[two_body.interaction]]
    type      = "compton"
    group1    = [1, 2]
    group2    = [3]
    interval  = 1
    tile_size = 5
    recoil1   = false
    recoil2   = true

[algorithms]
  current_filters = 0

  [algorithms.deposit]
    enable = false

  [algorithms.fieldsolver]
    enable = false

[particles]
  ppc0           = 2.0
  clear_interval = 1

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 1e6

  [[particles.species]]
    label    = "e+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 1e6

  [[particles.species]]
    label    = "ph"
    mass     = 0.0
    charge   = 0.0
    maxnpart = 1e6

[setup]
  temperature   = 0.01
  photon_energy = 1e-3

[output]
  interval_time = 0.1

  [output.fields]
    enable = false

  [output.particles]
    enable = false

  [output.spectra]
    log_bins = false
    e_min    = 0.0
    e_max    = 1.0
    n_bins   = 500

  [output.stats]
    quantities = ["T00_3"]

[checkpoint]
  keep = 0
