[simulation]
title           = <string>
runtime         = <float>

[domain]
coord_system    = <string> { X | XY | XYZ | R_PHI | R_THETA | R_THETA_PHI | logR_THETA_PHI }
resolution      = <array of int of size 1, 2 or 3>
extent          = <array of float of size 2, 4 or 6> [x1min, x1max, x2min, x2max, x3min, x3max]
boundaries      = <array of strings of size 1, 2 or 3> { PERIODIC | OPEN }

[algorithm]
CFL             = <float: 0 < ... < 0.5>
correction      = <float: ~1>
particle_shape  = <int> { 0 | 1 | 2 | 3 }

[units]
ppc0            = <float>
larmor0         = <float>
skindepth0      = <float>

[particles]
n_species       = <int>

[species_<INT>]
label           = <string>
mass            = <float>
charge          = <float>
maxnpart        = <int>
pusher          = <string> { BORIS }

[problem]
...
