[simulation]
title           = "Polar_example"
runtime         = 0.1

[domain]
coord_sys       = "spherical"
theta_h         = 0.0
resolution      = [64, 64]
extent          = [1.0, 5.0]
boundaries      = ["USER", "USER"]

[algorithm]
CFL             = 0.2
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01
