include = ["input.example.toml", "setups/**/*.toml"]
exclude = [".taplo.toml"]

[formatting]
  align_entries         = true
  align_comments        = true
  array_trailing_comma  = true
  array_auto_expand     = true
  array_auto_collapse   = true
  compact_arrays        = true
  compact_inline_tables = false
  inline_table_expand   = true
  compact_entries       = false
  column_width          = 80
  indent_tables         = true
  indent_entries        = true
  indent_string         = "  "
  trailing_newline      = true
  reorder_keys          = false
  reorder_arrays        = false
  allowed_blank_lines   = 2
  crlf                  = false

[schema]
  path    = "./.schema.json"
  enabled = false
