[simulation]
title           = "GR_example"
runtime         = 0.1

[domain]
qsph_r0         = 0.0
qsph_h          = 0.9
sph_rabsorb     = 8.0
resolution      = [64, 64]
extent          = [1.0, 20.0]
boundaries      = ["USER", "USER"]
a               = 0.99

[algorithm]
CFL             = 0.9
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01
