[simulation]
title           = "GR_example"
runtime         = 0.1

[domain]
sph_rabsorb     = 6.0              # radius of absorbing boundary in units of r_H
resolution      = [128, 128]
extent          = [0.9, 8.0]       # radial extent in units of r_H
boundaries      = ["USER", "USER"]
a               = 0.9

[algorithm]
CFL             = 0.9
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01

[visualization]
fields          = ["dx1", "dx2", "dx3", "bx1", "bx2", "bx3", "ex1", "ex2", "ex3", "hx1", "hx2", "hx3"]