[simulation]
title           = "GR_example"
runtime         = 0.1

[domain]
sph_rabsorb     = 5.5
resolution      = [256, 128]
extent          = [0.9, 6.0]       # Radial extent in units of the event horizon radius  
boundaries      = ["USER", "USER"]
a               = 0.99

[algorithm]
CFL             = 0.1
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01
