[simulation]
title           = "GR_example"
runtime         = 0.1

[domain]
sph_rabsorb     = 9.0
resolution      = [256, 128]
extent          = [1.4, 10.0]
boundaries      = ["USER", "USER"]
a               = 0.0

[algorithm]
CFL             = 0.4
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01
