[simulation]
  name = "fms"
  engine = "srpic"
  runtime = 400000.0

[grid]
  resolution = [81920]
  extent = [[0.0, 200.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"]]
    particles = [["PERIODIC"]]
    
[scales]
  larmor0 = 1.0
  skindepth0 = 1.0

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5
  
  [algorithms.synchrotron]
    gamma_rad = 10.0

  [algorithms.fieldsolver]
    # Yee - all 0.0 - default
    # 1D
    deltax = 0.0625
    # 2D
    deltay = 0.0
    betaxy = 0.0
    betayx = 0.0
    # 3D
    deltaz = 0.0
    betaxz = 0.0
    betazx = 0.0
    betayz = 0.0
    betazy = 0.0

[particles]
  ppc0 = 200.0

  [[particles.species]]
    label = "e-"
    mass = 1.0
    charge = -1.0
    maxnpart = 1e8
    cooling = "Synchrotron"

  [[particles.species]]
    label = "e+"
    mass = 1.0
    charge = 1.0
    maxnpart = 1e8
    cooling = "Synchrotron"

[setup]
  drift_ux = 0.0
  temperature = 1e-4
  Bz0 = 200.0
  amp = 0.1
  damp = 2000.0
  omega = 6.2e-6
  imax = 81910 #16370 # 262140
  iosc = 81800 #16000 # 262130

  lgrad = 1000.0
  pow = -2.0

[output]
  interval_time = 10.0
  format = "hdf5"

  [output.fields]
    quantities = ["N_1", "N_2", "B", "E", "T0i_1", "T0i_2", "Tij_1", "Tij_2", "J"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false

  # [output.debug]
  #   as_is = true
  #   ghosts = true

[diagnostics]
  colored_stdout = false

