[simulation]
  name = "vortex"
  engine  = "srpic"
  runtime = 20.0

[grid]
  resolution = [1024, 1024]
  extent     = [[0.0, 6.2831853], [0.0, 6.2831853]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields    = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]

[scales]
  larmor0    = 0.03
  skindepth0 = 0.015

[algorithms]
  current_filters = 8

  [algorithms.timestep]
    CFL = 0.5

  [algorithms.toggles]
    deposit = true
    fieldsolver = true

[particles]
  ppc0 = 20.0
  clear_interval = 100

  [[particles.species]]
    label    = "e-"
    mass     = 1.0
    charge   = -1.0
    maxnpart = 3e8
    pusher = "Boris"

  [[particles.species]]
    label    = "e+"
    mass     = 1.0
    charge   = 1.0
    maxnpart = 3e8
    pusher = "Boris"

[setup]
  temperature = 0.05
  Bg          = 2.0
  drift       = 0.1

[output]
  format        = "hdf5"

  [output.fields]
    interval_time = 0.1
    quantities = ["E", "J", "B", "Rho"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false

[diagnostics]
  interval = 2
  colored_stdout = true
  blocking_timers = true