[dependencies]
cuda   = "module:cuda/12.0"
cc     = "module:gcc/11.4"
mpi    = "module:$HOME/opt/.modules/ompi"
hdf5   = "module:$HOME/opt/.modules/hdf5"
kokkos = "module:$HOME/opt/.modules/kokkos"
adios2 = "module:$HOME/opt/.modules/adios2"

[entity]
modulepath = "$HOME/.modules/entity"

[entity.instances]
debug     = [true, false]
with_cuda = [true, false]
with_mpi  = [true, false]
archs     = ["ZEN2,AMPERE86", "ZEN2"]
