[dependencies]
cuda   = "module:cuda/11.8.0/gcc/11.3.0/zen2"
cc     = "module:gcc/11.3.0"
mpi    = ""
hdf5   = "module:hdf5"
kokkos = "module:$HOME/opt/.modules/kokkos"
adios2 = "module:$HOME/opt/.modules/adios2"

[entity]
modulepath = "$HOME/opt/.modules/entity"

[entity.instances]
debug     = [false]
with_cuda = [true]
with_mpi  = [false]
archs     = ["ZEN2,AMPERE80"]
