[simulation]
title           = "Example"
runtime         = 0.1

[domain]
resolution      = [256, 256]
extent          = [-2.0, 2.0, -2.0, 2.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.95
correction      = 1.0

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01

[problem]
amplitude       = 2.5
nx1             = 5
nx2             = 5
