[simulation]
title           = "Boris example"
runtime         = 0.1

[domain]
resolution      = [64, 64]
extent          = [-2.0, 2.0, -2.0, 2.0]
boundaries      = ["PERIODIC", "PERIODIC"]

[algorithm]
CFL             = 0.2
correction      = 1.0

[units]
ppc0            = 0.1
larmor0         = 0.25
skindepth0      = 0.01

[particles]
n_species       = 3

[species_1]
label           = "electron"
mass            = 1.0
charge          = -1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_2]
label           = "positron"
mass            = 1.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[species_3]
label           = "ion"
mass            = 2.0
charge          = 1.0
maxnpart        = 1e2
pusher          = "Boris"

[problem]
