[simulation]
title           = "Polar_example"
runtime         = 0.1

[domain]
metric          = "spherical"
qsph_r0         = 0.0
qsph_h          = 0.5
sph_rabsorb     = 8.0
resolution      = [128, 64]
extent          = [1.0, 10.0]
boundaries      = ["USER", "USER"]

[algorithm]
CFL             = 0.9
correction      = 1.025

[units]
ppc0            = 0.1
larmor0         = 0.1
skindepth0      = 0.01
