declare -r logfile="$(pwd)/${modulename_lower}.log"

function common_help {
  echo ""
  echo "Build and install $modulename"
  echo ""
  echo "usage: bash $programname --deploy -v --install_prefix <path> ... [options]"
  echo ""
  echo "  -h, --help                     print this help message"
  echo ""
  echo "  -d, --deploy                   execute the script"
  echo "                                 -d OFF shows the command to be executed"
  echo "                                 (default: $deploy)"
  echo ""
  echo "  -v, --verbose                  whether to print the compilation progress or not"
  echo "                                 (default: $verbose)"
  echo ""
  echo "  --install_prefix <path>        path to $modulename installation directory"
  echo "                                 (default: $default_install_prefix)"
  echo ""
  printf "%-33s%s" "  --${modulename_lower}_src_path <path>" "path to ${modulename} source directory"
  echo ""
  echo "                                 (default: $default_src_path/${modulename_lower})"
  if [ ! -z $has_modulefile ]; then
    echo ""
    printf "%-33s%s" "  --${modulename_lower}_module <path>" "path to ${modulename} module"
    echo ""
    echo "                                 set to OFF to disable modulefile installation"
    echo "                                 (default: $default_module_path/${modulename_lower})"
  fi
  echo ""
  echo "  --with-cc <path|module>        C compiler path or modulename (\`module:<modulename>\`)"
  echo "                                 (default: $default_with_cc)"
  echo ""
  echo "  --with-cuda <path|module>      CUDA path or modulename via (\`module:<modulename>\`)"
  echo "                                 set to OFF to disable CUDA support"
  echo "                                 (default: $default_with_cuda)"
  echo ""
}
