[simulation]
  name = "blob"
  engine = "srpic"
  runtime = 100.0

  [simulation.domain]
    decomposition = [2,1,1]

[grid]
  resolution = [1024, 1024]
  extent = [[-10.0, 10.0], [-10.0, 10.0]]

  [grid.metric]
    metric = "minkowski"

  [grid.boundaries]
    fields = [["PERIODIC"], ["PERIODIC"]]
    particles = [["PERIODIC"], ["PERIODIC"]]
    
[scales]
  larmor0 = 1.0
  skindepth0 = 1.0

[algorithms]
  current_filters = 4

  [algorithms.timestep]
    CFL = 0.5

[particles]
  ppc0 = 16.0

  [[particles.species]]
    label = "e-_p"
    mass = 1.0
    charge = -1.0
    maxnpart = 1e7

  [[particles.species]]
    label = "e+_p"
    mass = 1.0
    charge = 1.0
    maxnpart = 1e7

[setup]
  temp_1     = 1e-4
  x1c = -5.0
  x2c = 0.0
  v_max = 50.0
  dr = 1.0
  
[output]
  format = "hdf5"
  interval_time = 1.0

  [output.fields]
    quantities = ["N_1", "N_2", "B", "E"]

  [output.particles]
    enable = false

  [output.spectra]
    enable = false

[diagnostics]
  colored_stdout = false
