name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: python3 configure.py --kokkos_devices=Serial --compiler=g++
    - name: make test
      run: cd build && make test
