name: Premerge compilation on CPUs for all pgens

on:
  push:
  pull_request:
    types: [ready_for_review]

jobs:
  check-commit:
    runs-on: ubuntu-24.04
    outputs:
      run_tests: ${{ steps.check_message.outputs.run_tests }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check commit message
        id: check_message
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "ready_for_review" ]]; then
            echo "run_tests=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if git log -1 --pretty=%B | grep -q "COMPILEPGENS"; then
            echo "run_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_tests=false" >> "$GITHUB_OUTPUT"
          fi
  pgens:
    needs: check-commit
    if: needs.check-commit.outputs.run_tests == 'true'
    name: PGENS (mpi=${{ matrix.mpi }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        mpi: [ON, OFF]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install GCC 14 and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14 gfortran-14 build-essential wget libevent-dev libhwloc-dev 
          sudo apt-get install -y clang-format-20 clang-tidy-20
          pip3 install cmake-format --break-system-packages
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 50
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 50
          sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-14 50
          sudo ln -sf /usr/bin/clang-format-20 /usr/bin/clang-format
          sudo ln -sf /usr/bin/clang-tidy-20 /usr/bin/clang-tidy
          gcc --version
          g++ --version
          clang-format --version
          clang-tidy --version
          cmake-format --version
      - name: Install CMake (3.x)
        run: |
          sudo apt-get install -y cmake
          cmake --version
      - name: Install OpenMPI 5
        run: |
          if [ "${{ matrix.mpi }}" = "ON" ]; then
            sudo apt-get install -y libopenmpi-dev openmpi-bin
            mpirun --version
          fi
      - name: Check code formatting
        run: |
          ./dev/scripts/format.sh --verify
      - name: Compile all pgens
        run: |
          if [ "${{ matrix.mpi }}" = "ON" ]; then
            export CC=mpicc
            export CXX=mpicxx
          else
            export CC=gcc-14
            export CXX=g++-14
          fi
          ./dev/scripts/tests.sh --build build --with_pgens --flags "-D mpi=${{ matrix.mpi }}"
      - name: Check styling and guidelines
        run: |
          ./dev/scripts/tidy.sh --build build --verify --fast
