[simulation]
title   = "DepositSR"
runtime = 50.0

[domain]
qsph_r0     = 0.0
qsph_h      = 0.0
sph_rabsorb = 19.0
resolution  = [512, 512]
extent      = [0.8, 20.0]
boundaries  = [["CUSTOM", "ABSORB"], ["AXIS"]]

[algorithm]
CFL             = 0.5
current_filters = 4

[units]
ppc0       = 4.0
larmor0    = 2e-3
skindepth0 = 0.1

[particles]
n_species = 2

[species_1]
label    = "e-"
mass     = 1.0
charge   = -1.0
maxnpart = 1e2

[species_2]
label    = "e+"
mass     = 1.0
charge   = 1.0
maxnpart = 1e2

[problem]
x1  = [5.000, 15.0, 18.0, 4.0, 12.0]
x2  = [1.5707963268, 0.7853981634, 2.3561944902, 0.1, 3.0415926536]
x3  = [0.0, 0.0, 0.0, 0.0, 0.0]
ux1 = [5.0, 5.0, 5.0, 5.0, 5.0]
ux2 = [4.0, 7.0, 4.0, -5.0, 9.0]

[output]
fields        = ["E", "J", "divE"]
interval_time = 0.2
prtl_stride   = 1
flds_stride   = 1
particles     = ["X", "U"]
format        = "HDF5"
